### ISSUE TITLE
Serious bug that prevents gyroscope data from being included

### ISSUE THREAD

**Issue by gpdawson** [goatstone/AndroidSensorFusion#1]
private float timestamp;

The above declaration is faulty. It should be declared as a long.

It being declared as a float prevents any gyroscope rotation from being calculated, because the time interval between two timestamps is generally not within the precision capability of a float variable. Hence dT is always calculated as zero. Hence the rotation vector calculated from gyro is always (0, 0, 0).

**Comment by goatstone** [comment]
Graham,
Thanks for the input, changed the float to long. 
I was able to see the output, no longer just 0.
I can see it working better.
- Jose
