### ISSUE TITLE
Using GYRO mode with device without magnetometer 

### ISSUE THREAD

**Issue by vipulpurohit** [goatstone/AndroidSensorFusion#2]
Hello
Thanks for you great work.

When I try to use your lib in GYRO mode with the device without magnetometer it work well till I move my device, once I stop moving my device values of Azimuth, Roll and Pitch start moving toward zero and finally end up with settling at value 0.

Actually I'm drawing a cursor over my application using sensor movement with the help of your lib. I'm normalizing Azimuth and Roll values and computing the exact X and Y coordinates to draw the cursor.
 
Can you please help me to prevent the values from becoming zero after device become steady.

You can replicate my issue on device with magnetometer by disabling magnetometer sensor.

Thanks

**Comment by JoseHerminioCollas** [comment]
I was not able to replicate. Please try a new version of Android.
